### PR TITLE
Fixed wrong size passed to Interop_GenerateInstanceId.

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Review by steve-tucker — APPROVED** [review]
Is 40 the wrong size?

Edit: Yup.. 36, 40 definitely too big.

**Comment by nmoinvaz** [comment]
Yes at some point it was updated.

**Comment by sergio-nsk** [comment]
`sizeof` is ok for `char`. Let inform you about `std::size()` for arrays of other types.

**Comment by nmoinvaz** [comment]
The file is only .cc to be able to call the Steamworks API, otherwise it is just C.

**Pull request merged**
